version: '3.8'
services:
  web:
      container_name: "drf"
      build:
        context: .
        dockerfile: Dockerfile.prod
      command: gunicorn base.wsgi:application --bind 0.0.0.0:8000
      volumes:
        - static_volume:/home/app/web/staticfiles
      env_file:
        - ./.env.dev
      expose:
        - 8000
      depends_on:
        - db
  db:
      container_name: "psql"
      image: postgres
      volumes:
          - postgres_database_volume:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=post
  nginx:
    container_name: "nginx"
    build: ./nginx
    volumes:
        - static_volume:/home/app/web/staticfiles
    ports:
      - 80:80
    depends_on:
      - db

volumes:
  postgres_database_volume:
  static_volume: